import React, { useEffect, useState } from "react";
import { Loader, Projector } from "lucide-react";
import { toast } from "sonner";
import Projects from "../../../components/Dashboard/Projects";
import DeleteAllButton from "../../../components/Dashboard/Trash/DeleteAllButton";
import { motion } from "framer-motion";
import { containerVariants, itemVariants } from "../../../utils/MotionVariants";
import { useAPI } from "../../../context/ApiContext";
import { CardSkeleton } from "../../../components/common/CardSkeleton";

export default function TrashPage() {
  const { trashProjectsItems } = useAPI();
  const { trashProjects, loadingTrashProjects } = trashProjectsItems;

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="flex flex-col gap-6 relative"
    >
      <div className="flex justify-between items-center">
        <motion.div
          variants={itemVariants}
          className="flex flex-col items-start"
        >
          <h1 className="text-2xl font-semibold dark:text-primary backdrop-blur-lg">
            Trash
          </h1>
          <p className="text-base font-normal text-muted-foreground">
            All your deleted presentations
          </p>
        </motion.div>
        <DeleteAllButton Projects={trashProjects || []} />
      </div>

      {loadingTrashProjects ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map((_, i) => (
            <CardSkeleton key={i} />
          ))}
        </div>
      ) : trashProjects.length > 0 ? (
        <Projects projects={trashProjects} />
      ) : (
        <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-8">
          <Projector className="size-32" />
          <div className="flex flex-col items-center justify-center text-center">
            <p className="text-3xl font-semibold text-primary">
              Nothing to see here
            </p>
            <p className="text-base font-normal text-muted-foreground">
              So here is a random image generated by{" "}
              <span className="text-ufo">Creative AI</span>
            </p>
          </div>
        </div>
      )}
    </motion.div>
  );
}
