
export const defaultSlides = 

[
  {
    id: "slide-1",
    title: "Title Slide",
    background: "#ffffff",
    elements: [
      {
        id: "title-1",
        type: "text",
        position: { x: 240, y: 180 },
        size: { width: 480, height: 80 },
        zIndex: 1,
        properties: {
          text: "Marketing Presentation",
          fontSize: 48,
          bold: true,
          align: "center",
          color: "#333333",
        },
      },
      {
        id: "subtitle-1",
        type: "text",
        position: { x: 240, y: 280 },
        size: { width: 480, height: 40 },
        zIndex: 1,
        properties: {
          text: "Your Company Name",
          fontSize: 24,
          align: "center",
          color: "#666666",
        },
      },
    ],
  },
  {
    id: "slide-2",
    title: "About Us",
    background: "#f5f5f5",
    elements: [
      {
        id: "heading-2",
        type: "text",
        position: { x: 100, y: 50 },
        size: { width: 760, height: 60 },
        zIndex: 1,
        properties: {
          text: "About Our Company",
          fontSize: 36,
          bold: true,
          color: "#333333",
        },
      },
      {
        id: "text-2",
        type: "text",
        position: { x: 100, y: 130 },
        size: { width: 400, height: 300 },
        zIndex: 1,
        properties: {
          text: "We are a leading provider of innovative solutions in our industry. Our mission is to deliver exceptional value to our customers through cutting-edge technology and outstanding service.",
          fontSize: 18,
          lineHeight: 1.6,
          color: "#444444",
        },
      },
      {
        id: "image-2",
        type: "image",
        position: { x: 520, y: 130 },
        size: { width: 340, height: 300 },
        zIndex: 1,
        properties: {
          src: "/placeholder.svg?height=300&width=340",
          alt: "Company Image",
          borderRadius: 5,
        },
      },
    ],
  },
  {
    id: "slide-3",
    title: "Our Services",
    background: "#ffffff",
    elements: [
      {
        id: "heading-3",
        type: "text",
        position: { x: 100, y: 50 },
        size: { width: 760, height: 60 },
        zIndex: 1,
        properties: {
          text: "Our Services",
          fontSize: 36,
          bold: true,
          color: "#333333",
        },
      },
      {
        id: "service-1",
        type: "text",
        position: { x: 100, y: 130 },
        size: { width: 760, height: 40 },
        zIndex: 1,
        properties: {
          text: "• Strategic Consulting",
          fontSize: 20,
          bold: true,
          color: "#444444",
        },
      },
      {
        id: "service-2",
        type: "text",
        position: { x: 100, y: 180 },
        size: { width: 760, height: 40 },
        zIndex: 1,
        properties: {
          text: "• Product Development",
          fontSize: 20,
          bold: true,
          color: "#444444",
        },
      },
      {
        id: "service-3",
        type: "text",
        position: { x: 100, y: 230 },
        size: { width: 760, height: 40 },
        zIndex: 1,
        properties: {
          text: "• Digital Marketing",
          fontSize: 20,
          bold: true,
          color: "#444444",
        },
      },
      {
        id: "service-4",
        type: "text",
        position: { x: 100, y: 280 },
        size: { width: 760, height: 40 },
        zIndex: 1,
        properties: {
          text: "• Customer Support",
          fontSize: 20,
          bold: true,
          color: "#444444",
        },
      },
    ],
  },
  {
    id: "slide-4",
    title: "Market Analysis",
    background: "#f0f8ff",
    elements: [
      {
        id: "heading-4",
        type: "text",
        position: { x: 100, y: 50 },
        size: { width: 760, height: 60 },
        zIndex: 1,
        properties: {
          text: "Market Analysis",
          fontSize: 36,
          bold: true,
          color: "#333333",
        },
      },
      {
        id: "chart-4",
        type: "chart",
        position: { x: 100, y: 130 },
        size: { width: 760, height: 300 },
        zIndex: 1,
        properties: {
          chartType: "bar",
          data: "30,45,60,35,25",
          labels: "2020,2021,2022,2023,2024",
        },
      },
    ],
  },
  {
    id: "slide-5",
    title: "Contact Us",
    background: "#ffffff",
    elements: [
      {
        id: "heading-5",
        type: "text",
        position: { x: 100, y: 50 },
        size: { width: 760, height: 60 },
        zIndex: 1,
        properties: {
          text: "Contact Us",
          fontSize: 36,
          bold: true,
          color: "#333333",
        },
      },
      {
        id: "email-5",
        type: "text",
        position: { x: 100, y: 150 },
        size: { width: 760, height: 40 },
        zIndex: 1,
        properties: {
          text: "Email: contact@yourcompany.com",
          fontSize: 20,
          color: "#444444",
        },
      },
      {
        id: "phone-5",
        type: "text",
        position: { x: 100, y: 200 },
        size: { width: 760, height: 40 },
        zIndex: 1,
        properties: {
          text: "Phone: +1 (123) 456-7890",
          fontSize: 20,
          color: "#444444",
        },
      },
      {
        id: "address-5",
        type: "text",
        position: { x: 100, y: 250 },
        size: { width: 760, height: 40 },
        zIndex: 1,
        properties: {
          text: "Address: 123 Business Street, City, Country",
          fontSize: 20,
          color: "#444444",
        },
      },
      {
        id: "shape-5",
        type: "shape",
        position: { x: 600, y: 150 },
        size: { width: 200, height: 200 },
        zIndex: 1,
        properties: {
          shapeType: "circle",
          fill: "#f0f0f0",
          stroke: "#cccccc",
          strokeWidth: 2,
        },
      },
    ],
  },
]
