import React, { useEffect, useState } from "react";
import { Loader, Projector } from "lucide-react";
import { toast } from "sonner";
import Projects from "../../../components/Dashboard/Projects";
import { containerVariants, itemVariants } from "../../../utils/MotionVariants";
import { motion } from "framer-motion";
import { useAPI } from "../../../context/ApiContext";
import { CardSkeleton } from "./../../../components/common/CardSkeleton";

export default function SharedPage() {
  const { sharedProjectsItems } = useAPI();
  const { sharedProjects, loadingSharedProjects } = sharedProjectsItems;

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="flex flex-col gap-6 relative"
    >
      <motion.div variants={itemVariants} className="flex flex-col items-start">
        <h1 className="text-2xl font-semibold dark:text-primary backdrop-blur-lg">
          Shared
        </h1>
        <p className="text-base font-normal text-muted-foreground">
          All your shared presentations
        </p>
      </motion.div>

      {loadingSharedProjects ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map((_, i) => (
            <CardSkeleton key={i} />
          ))}
        </div>
      ) : sharedProjects.length > 0 ? (
        <Projects projects={sharedProjects} />
      ) : (
        <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-8">
          <Projector className="size-32" />
          <div className="flex flex-col items-center justify-center text-center">
            <p className="text-3xl font-semibold text-primary">
              Nothing to see here
            </p>
            <p className="text-base font-normal text-muted-foreground">
              So here is a random image generated by{" "}
              <span className="text-ufo">Creative AI</span>
            </p>
          </div>
        </div>
      )}
    </motion.div>
  );
}
