import { Projector } from "lucide-react";
import { useEffect, useState } from "react";
import Projects from "../../../components/Dashboard/Projects";
import { containerVariants, itemVariants } from "../../../utils/MotionVariants";
import { motion } from "framer-motion";
import axios from "axios";
import { BaseUrlApi, ErrorMessage } from "../../../lib/api";
import { toast } from "sonner";
import { CardSkeleton } from "../../../components/common/CardSkeleton";
import { useAPI } from "../../../context/ApiContext";

export default function ProjectsPage() {
  const { projectsItems } = useAPI();
  const { projects, loadingProjects } = projectsItems;

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="w-full flex flex-col gap-6 relative"
    >
      <div className="flex flex-col-reverse items-start w-full gap-6 sm:flex-row sm:justify-between sm:items-center">
        <motion.div
          variants={itemVariants}
          className="flex flex-col item-start"
        >
          <h1 className="text-2xl font-semibold dark:text-primary backdrop-blur-lg">
            Projects
          </h1>
          <p className="text-base font-normal text-muted-foreground ">
            All of your work in one place
          </p>
        </motion.div>
      </div>

      {/* Projects */}
      {loadingProjects ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map((_, i) => (
            <CardSkeleton key={i} />
          ))}
        </div>
      ) : projects.length !== 0 ? (
        <Projects projects={projects} />
      ) : (
        <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-8">
          <Projector className="size-32" />
          <div className="flex flex-col items-center justify-center text-center">
            <p className="text-3xl font-semibold text-primary">
              Nothing to see here
            </p>
            <p className="text-base font-normal text-muted-foreground ">
              So here is a random image generated by{" "}
              <span className="text-ufo">Creative AI</span>
            </p>
          </div>
        </div>
      )}
    </motion.div>
  );
}
